config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from . import setting 장고는 세팅을 불러올대 이렇게 하면 안됨!!


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    # http://localhost:8000/rooms/34 저기서 path("rooms/" ==> 8000/rooms/ 가 된다
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(
        "admin/",
        admin.site.urls,
    ),  # 처음의 path로 가서 장고가 확인할것이다!
]

# urlpatterns 은 지정된 이름이다
if settings.DEBUG:  # 내가 컴퓨터로 서버돌릴떄만 이렇게 쓴다!
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static이 경로를 가져다 주는것이다! 컨트롤 클릭해보셈
# URL은 settings.MEDIA_URL이것이고
# 이미지는 settings.MEDIA_ROOT 에서 가져온다!

core/urls.py
# config url page!!!
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config의 namespace

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
    # Homeview는 view로 전환해주는 메소드가 있다
    # path("", room_views.all_rooms, name="home"),  # "" 의 이미는 / 이다!
    # 장고가 볼때 장고가 url config가서 core url을 보고 온다!
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("<int:pk>/delete/", views.delete_reservation, name="delete"),
    path(
        "reservationList/",
        views.ReservationListView.as_view(),
        name="reservation-list",
    ),
    path(
        "reservationList_host/",
        views.ReservationListHostView.as_view(),
        name="reservation-list-host",
    ),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path(
        "<int:room_pk>/edit/delete/",
        views.delete_room,
        name="delete-room",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]
# 룸의 view가 def에서 class로 바뀌면서.. HomeView class처럼 바뀐다!

# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
# rooms/~~ 숫자가 <int:pk>가 된다!! 방의 id
# pk는 room_detail의 request, -> 다음 인자가 될것이다

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        # 예를들어 http://localhost:8000/users/verify/83bf208087cd4af3a526 에서
        # <str:key>는 83bf208087cd4af3a526를 의미한다! str은 그값이 str 이라는것이다!
        # key(아무이름이나됨)은 view 파일에서 complete_verification의 request 다음 받아온다!
        views.complete_verification,
        name="complete-verification",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting", views.switch_hosting, name="switch-hosting"),
    path("switch-language", views.switch_language, name="switch-language"),
]

templates/partials/footer.html
{% load i18n %}

<footer class="container mt-15vh mx-auto text-center py-10 border-t font-medium text-gray-500">
  <div class="flex flex-col">
    <span>
      {% trans "Please don't copy us." %}
    </span>
    <span>&copy; 2020 Kwangwooo Alex, Inc. {% trans "All rights reserved" %}.</span>
  </div>
  <div class="mt-10 flex">
    {% get_current_language as LANGUAGE_CODE %}
    <select class="w-1/5 h-8 p-px pl-3" id="js-lang">
      <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>English</option>
      <option value="fr" {% if LANGUAGE_CODE == 'fr' %} selected {% endif %}>French</option>
    </select>
  </div>
</footer>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
  {% for message in messages %}
  <li
    class="message font-medium bg-gray-700 rounded-full z-10 text-white py-4 px-6 w-3/12 text-center {% if message.tags %}{{ message.tags }}{% endif %}">
    {{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load i18n %}
<ul class="flex items-center text-sm font-medium h-full">
  {% if user.is_authenticated %}
  <!--로그인 되어있다면!!!-->
  <!--nav는 어떻게 user에 접근하는가? 
  Django는 context Processor함수가 있는데 template에 정보 추가하는역할 함
  어디서든 template에 접근할수있다, 이경우도 context Processor가있는데
  Cookie를 가지고 와서 user를 찾고 그걸 template에 자동으로 넣어줌!
  또한 절대 경로를 추가해줘야지만 admin에서 유저에서 view보기 버튼이 생김!>
  -->


  <li class="nav_link">
    <a href="{% url 'users:switch-hosting'  %}">
      {% if request.session.is_hosting %}
      <!--유저인지 호스트인지 세션을 체크 해야한다!-->
      {% trans "Stop hosting" %}
      {% else %}
      {% trans "Start hosting" %}
      {% endif %}
    </a>
  </li>

  {% if request.session.is_hosting %}
  <li class="nav_link"><a href="{% url 'rooms:create' %}">{% trans "Create Room" %}</a></li>
  <li class="nav_link"><a href="{% url 'reservations:reservation-list-host' %}">{% trans "Reservation(host)" %}</a></li>
  {% endif %}
  <li class="nav_link"><a href="{% url 'reservations:reservation-list' %}">{% trans "Reservation(guest)" %}</a></li>
  <!--reservations:reservation-list 의미는.. 앞에는 confing시작주소 뒤에는 reservation url-name이다! -->
  <li class="nav_link"><a href="{% url 'lists:see-favs' %}">{% trans "Favs" %}({{user.list.rooms.count}})</a></li>
  <li class="nav_link"><a href="{% url 'conversations:conversation' %}">{% trans "Msg" %}</a></li>
  <li class="nav_link"><a href="{{user.get_absolute_url}}">{% trans "Profile" %}</a></li>
  <li class="nav_link"><a href="{% url "users:logout" %}">{% trans "Log out" %}</a></li>

  {% else %}
  <!-- ml-8 마진 래프트만 8준다!-->
  <li class="nav_link"><a href="{% url "users:login" %}">{% trans "Log in" %}</a></li>
  <li class="nav_link"><a href="{% url "users:signup" %}">{% trans "Sign up" %}</a></li>
  {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
  <a
    href=" {% url 'users:github-login' %}"
    class="btn border-2 border-gray-700 text-gray-700 mb-2"
  >
    <i class="fab fa-github-alt mr-2 fa-lg"></i> Continue with Github
  </a>
  <a
    href="{% url 'users:kakao-login' %}"
    class="btn border border-yellow-400 text-yellow-800 mb-2 bg-yellow-400"
  >
    <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
  </a>
</div>

<div class="flex items-center w-full my-5">
  <div class="h-px w-full bg-gray-400"></div>
  <span class="text-gray-700 font-medium mx-2 text-sm">or</span>
  <div class="h-px w-full bg-gray-400"></div>
</div>