config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from . import setting 장고는 세팅을 불러올대 이렇게 하면 안됨!!


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    # http://localhost:8000/rooms/34 저기서 path("rooms/" ==> 8000/rooms/ 가 된다
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(
        "admin/",
        admin.site.urls,
    ),  # 처음의 path로 가서 장고가 확인할것이다!
]

# urlpatterns 은 지정된 이름이다
if settings.DEBUG:  # 내가 컴퓨터로 서버돌릴떄만 이렇게 쓴다!
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static이 경로를 가져다 주는것이다! 컨트롤 클릭해보셈
# URL은 settings.MEDIA_URL이것이고
# 이미지는 settings.MEDIA_ROOT 에서 가져온다!

core/urls.py
# config url page!!!
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config의 namespace

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
    # Homeview는 view로 전환해주는 메소드가 있다
    # path("", room_views.all_rooms, name="home"),  # "" 의 이미는 / 이다!
    # 장고가 볼때 장고가 url config가서 core url을 보고 온다!
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path(
        "<int:room_pk>/edit/delete/",
        views.delete_room,
        name="delete-room",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]
# 룸의 view가 def에서 class로 바뀌면서.. HomeView class처럼 바뀐다!

# urlpatterns = [path("<int:pk>", views.room_detail, name="detail")]
# rooms/~~ 숫자가 <int:pk>가 된다!! 방의 id
# pk는 room_detail의 request, -> 다음 인자가 될것이다

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")  # widget=forms.Textarea 넣으면 형식이 바뀐다!
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False, queryset=models.Amenity.objects.all()
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False, queryset=models.Facility.objects.all()
    )
    house_rules = forms.ModelMultipleChoiceField(
        required=False, queryset=models.HouseRule.objects.all()
    )
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = (
            "caption",
            "file",
        )

    def save(self, pk, *args, **kwargs):
        # pk값을 가져올수 없기떄문에... view.py에서
        # AddPhotoView클래스 안에서 form_valid 안의 메소드에 pk인자를 받을수있게
        # 다시 만든다!
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()
        # saved된 method를 intercepting 하고있다!
        # 왜냐하면 url에 있는 pk를 가져와야해서!
        # 조금 어려워서 23.5페이지 참고!


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        # 커밋 false는 object는 만들지만 db에 저장하지 않는다
        # 여기서 CreateRoomview (view파일안) 안에서 form_valid로 넘겨준다!
        return room

rooms/views.py
from django.http import Http404  # 방주인 아닌사람이 수정할려고할때 오류 낼려고 가져옴!
from django.views.generic import (
    ListView,
    DetailView,
    View,
    UpdateView,
    CreateView,
    FormView,
)
from django.shortcuts import render, redirect, reverse
from django_countries import countries
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms

# from django.http import Http404
# from django.shortcuts import render
# from math import ceil
# from django.shortcuts import render, redirect
# from django.urls import reverse
# from django.utils import timezone
# from django.core.paginator import Paginator, EmptyPage
# from datetime import datetime
# from django.http import HttpResponse

# Create your views here.
# 클래스를 만들어주면서 탬플릿 rooms에 room_list를 만들어줌
# 이름 바뀌면 안됨! 컴파일러가 원함! import, render 할필요가없다!!
# listView는 탬플릿 파일을 기본적으로 찾아본다!
# rooms가 appname이름이라 탬플릿파일속 rooms/room_list는 자동임
class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    # 정해져 있는 변수다.. 10줄기준으로 나눔.. 한줄로 끝!!!
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"

    # context 안의 내용을 좀더 수정한다!!!! 시간 추가!
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     now = timezone.now()
    #     context["now"] = now
    #     return context


# view를 더 쉽게 해보자!! 장고가 많이 도와주는 세번째 방식으로!
class RoomDetail(DetailView):
    """ RoomDetail Definition """

    model = models.Room  # 장고가 models.Room의 Room을 소문자로 바꿔
    # room detail.html 의 room 변수로 사용하게 만들어준다!!
    # view한테 우리가 무슨 model을 원하는지 알려줘야한다!


class SearchView(View):
    """ SearchView Definition """

    def get(self, request):
        country = request.GET.get("country")
        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():  # 애러가 없으면 리턴 true, 있으면 false
                # 여기 모든 왼쪽 값들은 룸 모델에서 가져온것이다!!
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")
                house_rules = form.cleaned_data.get("house_rules")

                # 장고가 알아서 파일 타입을 알고있기에 대입해준다!.
                # 장고 form안쓸때는 일일히 우리가 int str 등 타입에 맞게 해줬어야했다!!
                filter_args = {}
                # filter_args에 들어올때마다 if-> if-> if-> 탄다고 보면됨
                # 점점 걸러준다!

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type
                    # room_type.pk == room_type 이라고 보면된다!!
                    # 장고가 뛰어나서 알아서 해줌.. 걍 pk지워야함!

                if price is not None:
                    filter_args["price__lte"] = price
                    # lte => less than equals// price보다 낮은 가격을 찾아준다!

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                # print(bool(instant), bool(superhost))

                if instant_book is True:
                    filter_args["instant_book"] = True
                    # instant_book 이 True면 포함시켜주세요!

                if superhost is True:
                    filter_args["host__superhost"] = True

                    # if len(s_amenities) > 0:
                    # array 때문에 걸러줘야한다!!
                    # s_amenities에서 [1,2,3]을 가지고있다면 1,2,3을 필터에 하나하나 추가하는것!!
                for amenity in amenities:
                    filter_args["amenities"] = amenity  # __pk없어도된다!!!!!

                    # if len(s_facilities) > 0:  # array 때문에 걸러줘야한다!! 장고가 알아서 다처리해준다!
                for facility in facilities:
                    filter_args["facilities"] = facility

                    # if len(s_house_rules) > 0:  # array 때문에 걸러줘야한다!!
                for house_rule in house_rules:
                    filter_args["house_rules"] = house_rule
                # city + __startswith 에 의해 입력된 값으로 시작된 단어를 찾아준다! city에서!
                # 그래서 seo 입력경우 시티가 seoul인 경우 rooms에 들어가게된다!!
                # country 는 선택값이 정해져있기때문에 조건 없고 시작 글자도 필요없다!

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)
                return render(
                    request,
                    "rooms/search.html",
                    {"form": form, "rooms": rooms},  # form = forms.searchForm 에서 가져옴!
                )

        else:
            form = forms.SearchForm()
            # 종종 데이터 확인 작업없이 빈 form필요할때 있음, ex)처음 form화면!
            # request.GET을 해주면.. form에서 입력한게
            # 자동으로 서치 눌러도 같은 값을 가지고 있다!!
        return render(
            request,
            "rooms/search.html",
            {"form": form},  # form = forms.searchForm 에서 가져옴!
        )


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.Room
    template_name = "rooms/room_edit.html"  # 주소가 열리면 탬플릿 어디 위치하는지
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        # 이부분은 로그인한 사람이 방 주인이 아니면 edit을 못하게 해준다!
        room = super().get_object(queryset=queryset)
        # print(room.host.pk, self.request.user.pk) 지금 접속자랑 방 주인이랑 pk비교!
        if room.host.pk != self.request.user.pk:
            raise Http404()  # page not found 를 띄운다!
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):
    # 보호가 되는 roomDetail이다!
    # 오너면 포토를 볼수있다.
    # Detail of the room이다!
    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        # 이부분은 로그인한 사람이 방 주인이 아니면 edit을 못하게 해준다!
        room = super().get_object(queryset=queryset)
        # print(room.host.pk, self.request.user.pk) 지금 접속자랑 방 주인이랑 pk비교!
        if room.host.pk != self.request.user.pk:
            raise Http404()  # page not found 를 띄운다!
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            # 필터된 모든 사진을 삭제 한다! 근데 pk써서 pk에 맞는건 하나라 하나 삭제됨
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


@login_required
def delete_room(request, room_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            room.delete()
            # 필터된 모든 사진을 삭제 한다! 근데 pk써서 pk에 맞는건 하나라 하나 삭제됨
            messages.success(request, "Room Deleted")
        return redirect(reverse("core:home"))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    # SuccessMessageMixin등 상속 위치가 바뀌면 메시지가 안뜬다!!
    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    # SuccessMessageMixin 을 from에 추가하고 클래스에 추가헤서
    # 포토 수정시 photo updated 를 띄우게 한다!

    fields = ("caption",)
    # 필드는 부조껀 튜플이 되어야 한다!

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})

    # 사진 수정후 edit delete 페이지로 이동시킨다!


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):
    model = models.Photo
    template_name = "rooms/photo_create.html"
    fields = (
        "caption",
        "file",
    )
    form_class = forms.CreatePhotoForm
    # success_message = "Photo Uploaded"
    # SuccessMessageMixin 을 쓰면 formview를 쓸수없다!! 그래서 직접 만들어야함!

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)  # 이값은 forms CreatePhotoForm의 save()메쏘드로 넘길것임!
        messages.success(self.request, "Photo Uploaded")
        # 여기서는 success message를 대처함!
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):
    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        # form 의  def save return에서 룸을 가져온다!

templates/rooms/home(noneed).html
{% extends 'base.html' %}


<!-- 모두 같은 폴더잇다고 생각하고 경로 설정해야한다
<../base 이렇게 (절대경로) 해주면 안된다!!
block은 창문이다.. 자식이 부모 템플릿에게 content를 집어 넣을수 있게 하는!!  -->


{% block page_title %}
Home
{% endblock page_title %}

{% block content %}

<!--page.object_list 가 아니라 object_list로 바로 갈수있다-->
{% for room in page.object_list %}
<h1>{{room.name}} / ${{room.price}}</h1>
{% endfor %}


<!-- page=\{\{page-1\}\} 이 작동이 안한다.. 그래서 |add:
을 써서 페이지를 더하고 빼줄것이다. 장고 templates tags기능임! 
paginator에 num_pages 속성이 있음! 전체 페이지!!!-->
<h5>
  {% if page.has_previous %}
  <!-- <a href="?page={{page.number|add:-1}}">Previous</a>
  그리고  previous_page_number() 함수가 되어야하는데 장고 탬플릿은 () 안붙인다!-->
  <a href="?page={{page.previous_page_number}}">Previous</a>
  {% endif %}
  Page {{page.number}} of {{page.paginator.num_pages}}

  {% if page.has_next%}
  <!-- <a href="?page={{page.number|add:1}}">Next</a> if + has가 없었다면
  next_opage_number 에서 오류를 보낼것이다!-->
  <a href="?page={{page.next_page_number}}">Next</a>
  {% endif %}

</h5>


<!-- in다음에 range(1,page_count) 할려했으나 장고템플리이 
다 적용을 못해서.. view에서 변수값을 입력해 page_range를 불러왔다!
{% for page in page_range %}
<a href="?page={{page}}">{{page}}</a>
{% endfor %} // 다른걸 해보자!!
-->


{% endblock %}

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

  {% include 'mixins/room/room_form.html' with form=form name="Upload photo" %}

</div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked on_favs i18n%}


{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block content %}

<div class="container max-w-full h-75vh flex mb-20 -mt-5">
  <div class="h-full w-1/2 bg-cover bg-center" style="background-image:url({{room.first_photo}})"></div>
  <div class="h-full w-1/2 flex flex-wrap">
    {% for photo in room.get_next_four_photos  %}
    <div class="w-1/2 h-auto bg-cover bg-center border border-gray-500"
      style="background-image:url({{photo.file.url}})"></div>
    {% endfor %}
  </div>

</div>
<div class="container mx-auto flex justify-around pb-56">
  <div class="w-1/2">
    <div class="flex justify-between">
      <div class="mb-5">
        <h4 class=" text-3xl font-medium mb-px">{{room.name}}</h4>
        <span class="text-gray-700 font-light">{{room.city}}</span>
      </div>
      <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
        {% include "mixins/user_avatar.html" with user=room.host %}
        <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
      </a>
    </div>
    {% if user.is_authenticated %}
    {% on_favs room as on_favs_boolean %}
    <!-- on_fav 파일을 부른다! 결과를 불린으로 저장할것이다!-->
    {% if on_favs_boolean %}
    <a class="block mb-10 w-2/6 text-teal-600 font-bold"
      href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans "Remove from Favourites" %}</a>
    {% else %}
    <!-- ? 는 get방식할때.. ?id = 10 이런거! -->
    <a class="block mb-10 w-2/6 text-teal-600 font-bold"
      href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans "Save to Favourites" %}</a>
    {% endif %}
    {% endif %}
    <div class="flex border-section">
      <span class="mr-5 font-light">{{room.room_type}}</span>
      <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
      <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
      <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
      <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
      <!-- pluralize를 통해 복수가 되면 갯수가..s를 자동적으로 추가해준다!-->
    </div>
    <p class="border-section">
      {{room.description}}
    </p>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">Amenities</h4>
      {% for a in room.amenities.all %}
      <li class="mb-2">{{a}}</li>
      {% endfor %}
    </div>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">Facilities</h4>
      {% for f in room.facilities.all %}
      <li class="mb-2">{{f}}</li>
      {% endfor %}
    </div>
    <div class="border-section">
      <h4 class="font-medium text-lg mb-5">House Rules</h4>
      {% for r in room.house_rules.all %}
      <li class="mb-2">{{r}}</li>
      {% endfor %}
    </div>
    <div class="mt-10">
      <h4 class="font-medium text-2xl mb-5">Reviews</h4>
      <div class="flex items-center">
        <div>
          <i class="fas fa-star text-teal-500"></i>
          <span class="font-bold text-xl">{{room.total_rating}}</span>
        </div>
        <div class="h-4 w-px bg-gray-400 mx-5"></div>
        <div>
          <span class="font-bold text-xl">{{room.reviews.count}} </span>
          <span>review{{room.reviews.count|pluralize}}</span>
        </div>
      </div>
      <div class="mt-10">
        {% for review in room.reviews.all  %}
        <div class="border-section">
          <div class="mb-3 flex">
            <div>
              {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text="text-xl" %}
            </div>
            <div class="flex flex-col ml-5">
              <span class="font-mediu,">{{review.user.first_name}}</span>
              <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
              <!-- |의 이미가.. 앞에 값에서 뒤에껄 제한한다 의미와 또는 의미가 될수있다!
              date :'FY'는 장고 포멧에 맞춘거임! 달과 년도!-->
            </div>
          </div>
          <p>{{review.review}}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="w-1/3">
    {% if room.host == user %}
    <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
    {% else %}

    {% if not request.seesion.is_hosting %}

    {% for calendar in room.get_calenders  %}
    <div class="mb-20">
      <span class="text-center font-bold text-lg block mb-8">{{calendar.get_month}} / {{calendar.year}}</span>

      <div class="cal-grid font-semibold mb-4">
        {% for day in calendar.day_names %}

        <span>
          {{day}}
        </span>

        {% endfor %}
      </div>

      <div class="cal-grid">
        {% for day in calendar.get_days %}
        {% is_booked room day as is_booked_bool %}
        <!-- 다음과 같이 is_booked에 두개의 인자를 
        전달할수있다! 그리고 결과를 bool에저장한다-->
        {% if day.number != 0 %}
        {% if day.past %}
        <span class="cal-number bg-gray-200 text-gray-400">{{day}}</span>
        {% elif is_booked_bool %}
        <!-- true가 되는것들은 checkin과 checkout 사이의 날짜들이 된다!-->
        <span class="cal-number bg-gray-200 text-gray-400 line-through">{{day}}</span>
        {% else %}
        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}"
          class="cal-number bg-gray-200 text-gray-700 p-1 hover:bg-teal-400 hover:font-medium hover:text-white cursor-pointer">
          {{day}}
        </a>
        {% endif %}
        {%else%}
        <span></span>
        {% endif %}

        {% endfor %}
      </div>

    </div>
    {% endfor %}

    {% endif %}

    {% endif %}
  </div>
</div>

{% comment %} <div>
  <h1>{{room.name}}</h1>
  <h3>{{room.description}}</h3>
</div>
<div>
  <h2>By: <a href="{{room.host.get_absolute_url}}">{{room.host.username}}</a>
    {% if room.host.superhost %}
    (superhost)
    {% endif %}
  </h2>

  <!-- 룸에 의해 host 포린키로 되어있는 
  user의 속성 username도 가져올수있다!!-->

  <h3>Amenities</h3>
  <ul>
    {% for a in room.amenities.all %}
    <li>{{a}}</li>
    {% endfor %}
  </ul>

  <h3>Facilities</h3>
  <ul>
    {% for a in room.facilities.all %}
    <li>{{a}}</li>
    {% endfor %}
  </ul>

  <h3>House Rules</h3>
  <ul>
    {% for a in room.house_rules.all %}
    <li>{{a}}</li>
    {% endfor %}
  </ul> {% endcomment %}
</div>
{% endblock  %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div
  class="container mt-15vh lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

  {% include 'mixins/room/room_form.html' with form=form name="Update room" %}

  <div class="mt-5">
    <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
  </div>
  <div class="mt-5">
    <a href="{% url 'rooms:delete-room' room.pk %}" class="text-teal-500 font-medium">Delete room</a>
  </div>

</div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
{{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col">
  <div class="my-10 w-full">
    <a href="{% url 'rooms:add-photo' room.pk %}" room class="btn-link w-1/6 block">Upload Photo</a>
  </div>
  {% for photo in room.photos.all  %}
  <div class="mb-5 border p-6 border-gray-400 flex justify-between">
    <div class="flex items-start">
      <img src="{{photo.file.url}}" class="w-32 h-32" />
      <span class="ml-5 text-xl">{{photo.caption}}</span>
    </div>
    <div class="flex flex-col w-1/5">
      <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
      <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
      <!--room.pk photo.pk 인자를 두개주는 방법이다!-->
    </div>
  </div>
  {% endfor %}

  <div class="flex justify-center mt-5">
    <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 font-medium text-xl">Back to edit room</a>
    <!--{{room.get_absolute_url}}edit도 된다!-->
  </div>
</div>
{% endblock content %}