config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from . import setting 장고는 세팅을 불러올대 이렇게 하면 안됨!!


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    # http://localhost:8000/rooms/34 저기서 path("rooms/" ==> 8000/rooms/ 가 된다
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(
        "admin/",
        admin.site.urls,
    ),  # 처음의 path로 가서 장고가 확인할것이다!
]

# urlpatterns 은 지정된 이름이다
if settings.DEBUG:  # 내가 컴퓨터로 서버돌릴떄만 이렇게 쓴다!
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static이 경로를 가져다 주는것이다! 컨트롤 클릭해보셈
# URL은 settings.MEDIA_URL이것이고
# 이미지는 settings.MEDIA_ROOT 에서 가져온다!

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    # path("go/<int:a_pk>/<int:b_pk>/<int:c_pk>", views.go_conversation, name="go"),
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
    path("con/", views.ConversationView.as_view(), name="conversation"),
    path("con/<int:conversation_pk>/delete/", views.deleteConversation, name="delete"),
]

core/urls.py
# config url page!!!
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config의 namespace

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
    # Homeview는 view로 전환해주는 메소드가 있다
    # path("", room_views.all_rooms, name="home"),  # "" 의 이미는 / 이다!
    # 장고가 볼때 장고가 url config가서 core url을 보고 온다!
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("<int:pk>/delete/", views.delete_reservation, name="delete"),
    path(
        "reservationList/",
        views.ReservationListView.as_view(),
        name="reservation-list",
    ),
    path(
        "reservationList_host/",
        views.ReservationListHostView.as_view(),
        name="reservation-list-host",
    ),
]

reservations/models.py
import datetime
from django.db import models
from core import models as core_models
from django.utils import timezone

# from . import managers


class BookedDay(core_models.TimeStampedModel):
    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)  # str안하면.. 문자가 아니기떄문에 지울때 영향이갔음!


# Create your models here.
class Reservation(core_models.TimeStampedModel):
    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "confirmed"),
        (STATUS_CANCELED, "canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )

    # 유저랑 룸이 삭제되면 예약도 삭제될것이다!!

    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )
    # objects = managers.CustomReservationManager()

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    # 예약취소 확정같은 예약 상태도 만들수있음, 나중에 추가

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out
        # checkin과 checkout 을 보고 상태 를 결정한다

    in_progress.boolean = True  # X,O 로 상태를 표시해준다!!

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished  # 예약날짜가 끝날때마다 지워준다!

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            # 예약이 있는지 없는지 체크한다! None이면 우리가 생성하려는
            # 모델이 새로운 거라는 뜻이고
            # 그다음 우리는 start와 end date를 얻을 것이다!
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end), reservation=(self)
            ).exists()
            # 그래서 필터를 통해 start와 end사이에 bookedDay가 있는지 확인한다!
            # 존재한다면 existing_booked_day에 값이 들어갈것이다!
            if not existing_booked_day:
                # 존재하지 않는다면.. 우리는 reservation을 저장할거다
                super().save(*args, **kwargs)
                # 여기서 save 해주는 이유는 save를 해야 밑에 reseravtion의 FK를 줄수있음!
                for i in range(difference.days + 1):
                    # i는 0부터  range가 0부터시작한다!
                    day = start + datetime.timedelta(days=i)
                    # 새로운 날짜를 만들어 준다!
                    BookedDay.objects.create(day=day, reservation=self)
                    # 그리고 start와 end사이의 날짜들의 obejct bookedDay를 만들어 준다!
                    # class BookedDay(core_models.TimeStampedModel):
                    # day = models.DateField()
                    # reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)
                    # 여기 day값과 reservation 값을 넣어준것이다!
                    # reservation 가 포린키가 되는것이다!
                return
        return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


# Create your views here.


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        # booked day가있으면 다른 예약이 있다니깐 에러를 이르킨다!
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        # 룸을 못찾을 때 나온다!
        messages.error(request, "Can't Reserve That Room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        # 예약된게 없다면!!!
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
            # check_out은 하루 다음날.. 장고는 2일연속 못한다!
        )
        messages.success(
            request,
            f"Your reservation {date_obj}-{date_obj + datetime.timedelta(days=1)} has been saved successfully!",
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    # view를 쓰는이유는 컨트롤 하기 위해서! detail쓸수도 있으나..
    # detail보다 좀더 복잡하게 만들고 싶다
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        # reservation = models.Reservation.objects.get(pk=pk)
        # get은 결과를 찾지 못하면 error를 발생시킨다!.. DoesNotExist말고 다르게 해보자
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        # 여기 pk=pk 인자 값들은.. CustomReservationManager의 get or none의
        # **kwargs 의 쿼리 인자로 받을수있따!
        # managers 에 정의하고 model에 추가해서 쓸수있다!
        # 이 reservation은 guest나 host한테만 보여질 것이다!
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        # 페이지를 요청하는 user는 guest나 host여야 한다!
        # 즉 호스트도 게스트도 아니라면 http404를 raise한다!
        form = review_forms.CreateReviewForm()  # review의 폼을 받아와서 밑에 보내준다
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    # 여기 pk=pk 인자 값들은.. CustomReservationManager의 get or none의
    # **kwargs 의 쿼리 인자로 받을수있따!
    # managers 에 정의하고 model에 추가해서 쓸수있다!
    # 이 reservation은 guest나 host한테만 보여질 것이다!
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
        # 페이지를 요청하는 user는 guest나 host여야 한다!
        # 즉 호스트도 게스트도 아니라면 http404를 raise한다!
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        # print(models.BookedDay.objects.filter(reservation=reservation))
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


def delete_reservation(request, pk):
    user = request.user
    try:
        reservation = models.Reservation.objects.get(pk=pk)
        print(reservation)
        if user:
            reservation.delete()
            # 필터된 모든 사진을 삭제 한다! 근데 pk써서 pk에 맞는건 하나라 하나 삭제됨
            messages.success(request, "Reservation Deleted")
        else:
            messages.error(request, "Can't delete that Reservation")
        return redirect(reverse("reservations:reservation-list"))
    except models.Reservation.DoesNotExist:
        return redirect(reverse("reservations:reservation-list"))


class ReservationListView(TemplateView):
    template_name = "reservations/reservationList_detail.html"


class ReservationListHostView(TemplateView):
    template_name = "reservations/reservationListHost_detail.html"

templates/reservations/detail.html
{% extends "base.html" %}

{% block page_title %}
Reservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container mx-auto my-10 flex flex-col mt-15vh">
  <div class="border-t border-r border-l bg-cover bg-center h-56 rounded-t-lg"
    style="background-image: url({{reservation.room.first_photo}});">
  </div>

  <div class="flex flex-col items-start border-l border-r border-t border-b">
    <div class="font-medium border-b py-8 px-5 w-full">
      {{reservation.check_in}} - {{reservation.check_out}} <span
        class="ml-5 {%if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>
    </div>
    <!--reservation.get_status_display 이미 정해져있는 메소드다.. 
    model의 (STATUS_PENDING, "Pending") 의 "peding"을 가져온다
    class에도 조건을 걸수있음!-->

    <span class="text-2xl border-b p-5 mt-2 w-full">
      {{reservation.room.name}}
    </span>

    {% if reservation.room.host == user %}
    <div class="flex p-5 border-b w-full">
      <div class="flex flex-col items-center">
        {% include "mixins/user_avatar.html" with user=reservation.guest %}
        <span class="mt-2 text-gray-500">{{reservation.guest.first_name}}</span>
        </a>
      </div>
      <div class="ml-5 flex flex-col">
        <span class="font-medium mb-px">Contact this reservation's guest</span>
        <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk%}"
          class="font-medium text-teal-500">Send a new Message</a>
      </div>
    </div>
    {% else %}
    <div class="flex p-5 border-b w-full">
      <div class="flex flex-col items-center">
        {% include "mixins/user_avatar.html" with user=reservation.room.host %}
        <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
        </a>
      </div>
      <div class="ml-5 flex flex-col">
        <span class="font-medium mb-px">Contact your Airbnb Host</span>
        <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk%}"
          class="font-medium text-teal-500">Send a Message</a>
      </div>
    </div>
    {% endif %}

    <div class="py-10 px-5">
      {% if reservation.status != 'canceled' %}

      {% if reservation.status == 'confirmed' and reservation.is_finished and reservation.room.host != user%}
      <span class="font-medium text-2xl text-center w-fill block mb-5">Write your review</span>
      <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
        {% csrf_token %}
        {{form}}
        <button class="btn-link mt-5 bg-teal-500">Submit Review</button>
      </form>
      <a href="{% url 'reservations:delete' reservation.pk %}" class="btn-link block px-3 mt-5 mb-3 w-1/5 m-auto">Delete
        Reservation</a>

      {% else %}

      {% if reservation.status == "pending" %}
      <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-5">Cancel Reservation</a>

      {% if reservation.room.host == user %}
      <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mt-5 mb-3">Confirm
        Reservation</a>
      {% endif %}

      {% endif %}

      {% endif %}

      {% else %}
      <a href="{% url 'reservations:delete' reservation.pk  %}" class="btn-link block px-3 mt-5 mb-3">Delete
        Reservation</a>
      {% endif %}
    </div>

  </div>


</div>
{% endblock content %}

templates/reservations/reservationListHost_detail.html
{% extends "base.html" %}

{% block page_title %}
Guests' reservations
{% endblock page_title %}


{% block content %}
<div class="h-75vh">

  <h3 class="mb-12 text-2xl text-center font-bold pt-10">Guests' reservations to your rooms</h3>

  <div class="container mx-auto pb-10 flex flex-col items-center">
    <div class="flex flex-wrap w-full -mx-40 mb-10">
      {% for room in user.rooms.all %}
      {% for reservation in room.reservations.all %}
      {% include "mixins/reservationHost_card.html" with room=reservation.room reservation=reservation %}
      {% endfor %}
      <!--for문의 room을 가져온다! 왼쪽룸이 저 include안으로 가고 오른쪽룸이 for문의 room이다-->
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

templates/reservations/reservationList_detail.html
{% extends "base.html" %}

{% block page_title %}
{{user.first_name}}'s reservations
{% endblock page_title %}


{% block content %}
<div class="h-75vh">

  <h3 class="mb-12 text-2xl text-center font-bold pt-10">Your reservations<br>
    <span class="text-sm">Please leave your review when your
      reservation's status is
      <span class="text-indigo-500">'finished'</span></span></h3>

  <div class="container mx-auto pb-10 flex flex-col items-center">
    <div class="flex flex-wrap w-full -mx-40 mb-10">
      {% for reservation in user.reservations.all %}
      {% comment %} {{reservation.room.description}} {% endcomment %}
      {% include "mixins/reservation_card.html" with room=reservation.room reservation=reservation %}
      <!--for문의 room을 가져온다! 왼쪽룸이 저 include안으로 가고 오른쪽룸이 for문의 room이다-->
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}