config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from . import setting 장고는 세팅을 불러올대 이렇게 하면 안됨!!


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    # http://localhost:8000/rooms/34 저기서 path("rooms/" ==> 8000/rooms/ 가 된다
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(
        "admin/",
        admin.site.urls,
    ),  # 처음의 path로 가서 장고가 확인할것이다!
]

# urlpatterns 은 지정된 이름이다
if settings.DEBUG:  # 내가 컴퓨터로 서버돌릴떄만 이렇게 쓴다!
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static이 경로를 가져다 주는것이다! 컨트롤 클릭해보셈
# URL은 settings.MEDIA_URL이것이고
# 이미지는 settings.MEDIA_ROOT 에서 가져온다!

core/urls.py
# config url page!!!
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config의 namespace

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
    # Homeview는 view로 전환해주는 메소드가 있다
    # path("", room_views.all_rooms, name="home"),  # "" 의 이미는 / 이다!
    # 장고가 볼때 장고가 url config가서 core url을 보고 온다!
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        # 예를들어 http://localhost:8000/users/verify/83bf208087cd4af3a526 에서
        # <str:key>는 83bf208087cd4af3a526를 의미한다! str은 그값이 str 이라는것이다!
        # key(아무이름이나됨)은 view 파일에서 complete_verification의 request 다음 받아온다!
        views.complete_verification,
        name="complete-verification",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting", views.switch_hosting, name="switch-hosting"),
    path("switch-language", views.switch_language, name="switch-language"),
]

users/models.py
import uuid  # 번호 무작위 생성!! 8진수 가능(메일검증위해!)
from django.utils.translation import gettext_lazy as _  # reverse lazy같은것임!
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.shortcuts import reverse
from django.template.loader import render_to_string  # 탬플릿을 load해서 render 한다!

# 유저파트는 위에것을 import 해서 사용할것이다..


# Create your models here.
# 장고 속의 models속의 class Model을 사용한다!!
# core_models.TimeStampedModel은 사용안한다. DB에 저장해야하기떄문에
class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, _("Male")),
        (GENDER_FMALE, _("Female")),
        (GENDER_OTHER, _("Other")),
        # GENDER_~~ 가 DB로 갈 값이고, Male이 form에 보여질 속성이다.
        # 번역을 위한 _() 위에서 _로 정의하였음!
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, _("English")),
        (LANGUAGE_KOREAN, _("Korean")),
    )

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"

    CURRENCY_CHOICES = (
        (CURRENCY_USD, "USD"),
        (CURRENCY_KRW, "KRW"),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"
    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    # blank ="true"는 form에서 빈공간을 빨간색표시하는데 저걸이용해 무시할수있다.
    gender = models.CharField(
        _("gender"), choices=GENDER_CHOICES, max_length=10, blank=True
    )
    # 비어도 괜찮다!.. choices는 내장된 속성!! 3개의 값을 가지게 한다!

    bio = models.TextField(_("bio"), blank=True)
    bio2 = models.TextField(_("bio2"), blank=True)
    # 여기에 뭘넣던 admin패널에 다생기게 된다. database에 넣을수있음
    # default값 은 무조껀 있어야 migrations 만든후 migrate 넘길수있다
    # 값을 뭐라도 넣어줘야 한다. 안그러면 db에 빈자리 처리가 안된다!
    # 또는 null=true 라고 적어줘서 빈칸 써도 된다고 해준다!!
    birthdate = models.DateField(blank=True, null=True)
    language = models.CharField(
        _("language"),
        choices=LANGUAGE_CHOICES,
        max_length=2,
        blank=True,
        default=LANGUAGE_KOREAN,
    )
    currency = models.CharField(
        choices=CURRENCY_CHOICES, max_length=3, blank=True, default=CURRENCY_KRW
    )
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    # 이메일 시크릿은 유저가 아이디와 비번 만들면 시크릿 숫자를 추가할것이다!

    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    # user Detail 안에 있는 모델을 보기 위해서..URL을 반환 해야한다
    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]  # 무작위 숫자 8진수후 20자리 가져오기!
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            # (f'To verify your account click <a href="http://localhost:8000/users/verify/{secret}">here</a>',)
            send_mail(
                # 여기서 중요한것은 message를 보낼때 텍스트는 택스트대로
                # html은 html 로 따로 보내야한다는 점이다! 그래서
                # 메시지를 html을 제외한 택스트 보내주는거 하나 strip_tags(html_message)
                # 메시지를 html만 뽑은거 하나를 보내주는것이다!
                _("Verify Kwangwoo_BNB Account"),
                strip_tags(html_message),  # html형태를 제외하고 return함
                # f'To verify your account click <a href="http://localhost:8000/users/verify/{secret}">here</a>',
                # string형태로 가서 href 가 안먹힐 것이다!
                settings.EMAIL_FROM,  # 세팅에서 들고옴!
                [self.email],  # 유저에게 보낸다!
                fail_silently=False,  # 애러 신경안쓴다!
                html_message=html_message,
            )
            self.save()  # 이과정을 다하고 저장한다!email_secret 같은것들이
        return

    # 모든 클래스는 밑의 매소드를 가지고 있다.
    # def __str__(self):
    #   return self.username

users/views.py
import os
import requests
from django.utils import translation
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile  # 사진보여줄때 필요!
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin  # 프로필 업데이트하면 나오게한다!
from . import forms, models, mixins

# from django.contrib.auth.forms import UserCreationForm # 여기안하고 form에 적용할거임


# Create your views here.
class LoginView(mixins.LoggedOutOnlyView, FormView):
    # 이걸 쓰면 get, post 할필요가없다!

    template_name = "users/login.html"
    form_class = forms.LoginForm
    # success_url = reverse_lazy("core:home") 이거대신 get_success_url을 씀!
    # reverse는 실제 URL을 준다!
    # reverse_lazy는 바로 실행하지 않는다!
    # 필요할때만 실행한다!
    # 뷰를 불러올때 URL이 아직 불러와지지 않은것이다!
    # 조금 어려운부분이다.. url이 불러 지지않는데 필요할때
    # 바로 가져오게 해주는 lazy를 쓴다고 생각하자!
    # form 에서 제일 좋은점은 우리가 is_valid 같은거 안해도됨!
    # 하나만 하면된다 form_valid!!!

    def form_valid(self, form):  # form이 유효한지만 체크하면 된다!
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, f"Welcome back {user.first_name}")
        return super().form_valid(form)
        # 이게 호출되면 successURL에 다시가고
        # 다시 다 작동된다!

    def get_success_url(self):
        # LoggedOutOnlyView 가 작동이되면.. airbnb문서 196장에 잘 써놧음!
        # 주소 마지막에 갈려고했던곳..이 next=???로적힌다 그래서 next를 받아오는것이다!
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, f"See you later")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm  # forms에 정의되어있는 클래스임!
    # 비밀번호 (깃허브, 카톡을 위해 form_class를 다른것으로 바꿔준다!)
    # form_class = UserCreationForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()  # form이 유효하다면!
        # forms.py에서 만들어진 (form_class = forms.SignUpForm) 형식이 저장된다!
        # 저장하고 다시 로그인해준다!. 회원가입후 사용자가 다시 로그인할필요 없음!
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, f"Welcome {user.first_name}")
        if user.email == "bnc3049@gmail.com":
            user.verify_email()
            # # user.model파일에 있는 함수를 사용한다!
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True  # 여기서 확인했다고 알려준다! False=>True
        user.email_secret = ""
        # 메일열고 here 클릭하기전까지는 admin에 secret이 저장되어있음

        user.save()  # 장고 signupview에 자동 저장 기능이있다!
        # to do : add success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


# 유저가 깃허브 눌렀을때 /user/login/github링크로갈껀데 redirect 쪽으로 가진다!
def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://localhost:8000/users/login/github/callback"  # 깃허브의 Authorization callback URL
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


# 유저가 accept를 누르면 여기로 온다!! 또한 url에서 code를 가져온다
# http://localhost:8000/users/login/github/callback?code=80bd88bcaafc31e583ee
# 저기서 code=~~~~ 되어있는 부분! 이코드로 우리는 다시 다른 request를 보낼것이다!
# token_access 한다 with client_id, client_secret, code를 이용해서!
# 그다음 깃허브는 우리에게 json을 줄것이고!!(result값으로..)
# 그다음 애러가 있는지 체크 할것이다!
# 에러가 없다면 (else)에서 access_token을 가져올것이다!
# 그 access_token을 가지고 깃허브 api를 request할수있게 된다!
# 헤더에서 토큰을 보내고 그다음 우리는 profile json을 받게된다!
# 그다음 profile json안에 username이 있는지 체크할것이다!
# profile_json 속에 이름이 없다면 리다이렉해준다!


class GithubException(Exception):
    # 이름을 우리껄로 만들었고.. redirect대신 exception을 사용해준다!
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        # code를 access token으로 바꿔야한다! 깃허브 api를 access 할수있게 해준다!
        # 우리가 해야하는건 post request를 보내야 한다!
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )  # 값을 제이슨으로 넘겨준다고 깃에 쓰어있음!!
            token_json = token_request.json()
            error = token_json.get("error", None)
            # 토큰json에서 에러를 포함한 문서가있는지 봐야한다
            # 예를 들어 유효하지 않은 코드가 왔을때!.. 시간지났던지..등등
            if error is not None:
                # return redirect(reverse("users:login"))
                raise GithubException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                # 깃허브 API에 request를 보내는걸 만들거임!
                profile_request = requests.get(
                    # 그 access_token을 가지고 깃허브 api를 request할수있게 된다!
                    "https://api.github.com/user",
                    # emails를 써서 프라이빗 메일도 찾아줌! 또는 깃헙 프리베이트 메일해제!
                    # 프리벳 문제생기면 !! 이부분 손봐야함!!
                    # 헤더에서 토큰을 보내고
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                # print(profile_request)
                # 내가만든설명서에 있음 3단계에 적혀있다!! 시키는데로 설명서보고 하는중..
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    # user가 있다면 계속 진행
                    # 이것들을 깃허브에서 가져온다!!
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")

                    # 그 이메일을 가진 유저가 있다면 그말은 이미 로그인 되어 있다는 뜻이다.
                    # 그 이메일을 가진 user가 있다는 뜻이다
                    try:
                        user = models.User.objects.get(email=email)
                        # 만약 우리가 유저를 찾았다면 로그인 메소드를 확인할것이다
                        if user.login_method != models.User.LOGIN_GITHUB:
                            # trying to log in 여기 온다는건 밑에 모든 조건을 다 거쳤다는것이다!
                            # 만약 로그인메쏘드가 깃허브면 유저를 로그인 시킬것이다!
                            # login(request, user) 밑에서 한번에 해줌
                            raise GithubException(
                                f"Please log in with: {user.login_method}"
                            )

                    except models.User.DoesNotExist:
                        # 만약 우리가 한명의 유저도 찾을 수 없다면.. 그뜻은
                        # 우리가 유저를 만들어야한다는 의미 이다!
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                            # 이유저는 깃허브로 부터 왔다!
                        )
                        user.set_unusable_password()
                        # 어떤 패스워드가 됐던 먹히지 않고
                        # 로그인 시킬것이다!
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))

                else:
                    # return redirect(
                    #     reverse("users:login")
                    # )  # profile_json 속에 이름이 없다면 리다이렉해준다!
                    raise GithubException("Can't get your profile")
        else:
            # return redirect(reverse("core:home"))
            # 코드가 none이면
            raise GithubException("Can't get code")
    except GithubException as err:  # 에러나면 걍 로그인으로 보냄
        messages.error(request, err)
        return redirect(reverse("users:login"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://localhost:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://localhost:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )  # 여기서 access token을 얻는다!
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code")
        access_token = token_json.get("access_token")
        # if 검사후 json에 access token이 있다.. get으로 가져온다!
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",  # 와... 한칸 띄워져 있었다고 404오류 계쏙남... me다음에
            headers={"Authorization": f"Bearer {access_token}"},

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}


<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

  {% include "partials/social_login.html" %}
  {% include "mixins/auth/auth_form.html" with form=form name="Log in"%}
  {% comment %} 위에껄로 하나로 로그인과 사인업을 겹쳤다! 필드만 검사해주면돼서
  필드를 검사하는 방식만 auth_form에 넣어줌!
  <form method="POST" action="{% url "users:login" %}" class="w-full">
    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <span class="text-red-700 font-medium text-sm">{{error}}</span>
    {% endfor%}
    {% endif %}
    <!-- csrf_token 을 이용하여 login쪽에만 so post를 받게 한다!!
    다른곳에서 정보를 가로채 갈수 없게 한다!-->
    <!--{{form.as_p}}
    <input type="email" placeholder="Email" class="mb-3">
    <input type="password" placeholder="Password" class="mb-3">
    교체해준다.. form.as_p는 양식 적용이안돼서..
    -->

    {% for field in form  %}
    {% include "partials/form_input.html" with field=field %}
    {% endfor %}

    <button class="btn bg-red-500 text-white">Login</button>
  </form>{% endcomment %}

  <div class="mt-5">
    <span class="mr-2">Don't have an account? </span>
    <a href="{% url "users:signup" %}" class="text-teal-500 font-medium">Sign up</a>
  </div>

</div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
  {% include "partials/social_login.html" %}

  {% include "mixins/auth/auth_form.html" with form=form name="Sign up"%}
  <!-- name = sign up을 auth_form에서 가져갈수있게 해준다! -->

  <div class="mt-5">
    <span class="mr-2">Have an account?</span>
    <a href="{% url "users:login" %}" class="text-teal-500 font-medium">Login</a>
  </div>


</div>
{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="min-h-75vh mt-15vh">
  <div
    class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/auth/auth_form.html' with form=form name="Update Password" %}
  </div>
</div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div
  class="container mt-15vh lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

  {% include 'mixins/auth/auth_form.html' with form=form name="Update profile" %}

  {% if object.login_method == "email" %}
  <div class="mt-5">
    <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">Change Password</a>
  </div>

  {% endif %}

</div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
{{user_obj.first_name}}'s Profile
{% endblock page_title %}


{% block content %}

{% if user_obj.rooms.count < 5 %}
<div class="h-75vh mt-15vh">
  {%else%}
  <div>
    {% endif %}
    <div
      class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
      {% include "mixins/user_avatar.html" with user=user_obj%}
      <!--with을 통해 include 안으로 변수를 넘겨준다 생각하면됨 이파일의 user_obj는
  include파일 안으로 들어가서 user가 됩니다 라는 뜻임!-->

      <div class="flex items-center">
        <span class=" text-3xl mt-1">{{user_obj.first_name}} </span>
        {% if user_obj.superhost %}
        <i class="fas fa-check-circle text-teal-400 ml-1"></i>
        {% endif %}
      </div>

      <span class="text-lg text-center mb-5">{{user_obj.bio}}</span>

      {% if user == user_obj %}
      <a href="{% url "users:update" %}" class="btn-link">Edit Profile</a>

      {% endif %}

      <!--{{Hello}}-->
    </div>

    {% if user_obj.rooms.count > 0 %}
    <div class="container mx-auto pb-10 flex flex-col items-center">
      <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Rooms</h3>
      <div class="flex flex-wrap w-full -mx-40 mb-10">
        {% for room in user_obj.rooms.all %}
        {% include "mixins/room_card.html" with room=room %}
        <!--for문의 room을 가져온다! 왼쪽룸이 저 include안으로 가고 오른쪽룸이 for문의 room이다-->
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>

  {% endblock content %}